server:
  port: 0
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
  application:
    name: product-service
eureka:
  client:
    fetch-registry: true
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
#flyway:
#  enabled: true
#  locations: classpath:common